[package]
name = "tetris"
version = "0.1.0"
authors = ["asufanah@gmail.com"]
edition = "2018"

[dependencies]
rand = "0.6"
pancurses = "0.16"
ctrlc = "3.1.4"
exitcode = "1.1.2"
device_query = "0.2.4"
