version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: build
          command: cargo build
      - run:
          name: test
          command: cargo test

